name: Test
on: pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run server in background
        run: npm run dev-start &

      - name: Wait for server to start
        run: sleep 10

      - name: Run tests
        run: npm run test
